#include "u8g2_glue.h"

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#include <driver/i2c.h>
#include <esp_err.h>
#include <esp_log.h>
#include <esp_rom_sys.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>

#include "boards/board.h"

#define TAG "U8G2"

/*
 * IMPORTANT:
 * BOARD_OLED_ADDR must be the 7-bit I2C address: 0x3C.
 * Do NOT use 0x3C << 1 here.
 *
 * U8G2 internally stores the address as 0x78, but this ESP-IDF
 * hardware callback uses OLED_ADDR directly with i2c_master_write_to_device().
 */
#define OLED_PORT BOARD_OLED_I2C_PORT
#define OLED_ADDR BOARD_OLED_ADDR

/*
 * The SSD1306 CAD layer already generates the I2C control byte:
 *   0x00 = command stream
 *   0x40 = display data stream
 *
 * Therefore this callback MUST NOT add 0x00/0x40 and MUST NOT use DC
 * to construct a control byte.
 *
 * Keep one complete U8X8 transfer in one I2C transaction. This is
 * especially important for u8x8_cad_ssd13xx_fast_i2c().
 */
#define TXBUF_SIZE 1024

static uint8_t txbuf[TXBUF_SIZE];
static size_t txlen = 0;
static bool transfer_active = false;

static uint8_t u8x8_i2c_flush(void)
{
    if (txlen == 0)
        return 1;

    esp_err_t err = i2c_master_write_to_device(
        OLED_PORT,
        OLED_ADDR,
        txbuf,
        txlen,
        pdMS_TO_TICKS(100)
    );

    txlen = 0;

    if (err != ESP_OK) {
        ESP_LOGE(TAG, "SSD1306 I2C write failed: %s", esp_err_to_name(err));
        return 0;
    }

    return 1;
}

uint8_t u8x8_byte_hw_i2c(
    u8x8_t *u8x8,
    uint8_t msg,
    uint8_t arg_int,
    void *arg_ptr)
{
    (void)u8x8;

    switch (msg) {
    case U8X8_MSG_BYTE_INIT:
        txlen = 0;
        transfer_active = false;
        return 1;

    case U8X8_MSG_BYTE_START_TRANSFER:
        /*
         * Do not write anything to the bus here.
         * Just start collecting the exact bytes generated by the CAD layer.
         */
        if (transfer_active) {
            /* Defensive recovery; normally CAD closes the previous transfer. */
            if (!u8x8_i2c_flush()) {
                transfer_active = false;
                return 0;
            }
        }

        txlen = 0;
        transfer_active = true;
        return 1;

    case U8X8_MSG_BYTE_SEND: {
        const uint8_t *data = (const uint8_t *)arg_ptr;

        if (arg_int == 0)
            return 1;

        if (data == NULL)
            return 0;

        /* Never split a transaction without another SSD1306 control byte. */
        if (!transfer_active || txlen + arg_int > TXBUF_SIZE) {
            ESP_LOGE(TAG, "Invalid U8G2 I2C transfer: len=%u active=%d",
                     (unsigned)(txlen + arg_int), transfer_active ? 1 : 0);
            return 0;
        }

        for (uint8_t i = 0; i < arg_int; ++i)
            txbuf[txlen++] = data[i];

        return 1;
    }

    case U8X8_MSG_BYTE_END_TRANSFER:
        if (!transfer_active)
            return 1;

        transfer_active = false;
        return u8x8_i2c_flush();

    case U8X8_MSG_BYTE_SET_DC:
        /*
         * SSD1306 I2C has no DC pin.
         * The CAD layer puts 0x00/0x40 into the byte stream itself.
         */
        return 1;

    default:
        return 1;
    }
}

uint8_t u8x8_gpio_and_delay_esp32(
    u8x8_t *u8x8,
    uint8_t msg,
    uint8_t arg_int,
    void *arg_ptr)
{
    (void)u8x8;
    (void)arg_ptr;

    switch (msg) {
    case U8X8_MSG_GPIO_AND_DELAY_INIT:
        return 1;

    case U8X8_MSG_DELAY_MILLI:
        vTaskDelay(pdMS_TO_TICKS(arg_int));
        return 1;

    case U8X8_MSG_DELAY_10MICRO:
        esp_rom_delay_us((uint32_t)arg_int * 10U);
        return 1;

    case U8X8_MSG_DELAY_100NANO:
        return 1;

    case U8X8_MSG_GPIO_RESET:
        /* OLED module has no MCU-controlled RESET in this project. */
        return 1;

    case U8X8_MSG_GPIO_CS:
    case U8X8_MSG_GPIO_DC:
        /* Not used by SSD1306 I2C. */
        return 1;

    default:
        return 1;
    }
}
